import { useState, useEffect, useRef, useCallback } from 'react'
import { Link } from 'react-router-dom'
import { motion, useInView, useScroll, useTransform } from 'framer-motion'

/* ═══════════════════════════════════════════════════════════
   CONSTANTS
   ═══════════════════════════════════════════════════════════ */

const LANGUAGES = [
  { name: 'JavaScript', ext: '.js',  icon: '{ }' },
  { name: 'TypeScript', ext: '.ts',  icon: '<T>' },
  { name: 'Python',     ext: '.py',  icon: '#!'  },
  { name: 'Java',       ext: '.java',icon: '::' },
  { name: 'Go',         ext: '.go',  icon: ':=' },
  { name: 'Rust',       ext: '.rs',  icon: '&mut' },
  { name: 'C++',        ext: '.cpp', icon: '<<' },
]

const FEATURES = [
  {
    title: 'Real-Time Metrics',
    desc: 'WPM, raw WPM, accuracy and error count — updated on every keystroke with smooth live charts.',
    icon: '▸ _',
  },
  {
    title: 'AI-Powered Snippets',
    desc: 'Fresh, syntax-accurate code generated by Google Gemini. Never practice the same snippet twice.',
    icon: '⚡',
  },
  {
    title: 'Global Leaderboard',
    desc: 'Compete with developers worldwide. Per-language rankings with podium display for the top 3.',
    icon: '🏆',
  },
  {
    title: 'Personal Analytics',
    desc: 'GitHub-style activity heatmap, per-duration breakdowns, consistency scores and progress tracking.',
    icon: '📊',
  },
  {
    title: 'Multiple Durations',
    desc: 'Sprint or endurance — choose 15s, 30s, 60s or 120s tests to match your training goals.',
    icon: '⏱',
  },
  {
    title: 'Difficulty Levels',
    desc: 'Easy, medium or hard. Scale the complexity from simple functions to advanced algorithms.',
    icon: '◈',
  },
]

const DEMO_CODE = `function quickSort(arr) {
  if (arr.length <= 1) return arr;
  const pivot = arr[0];
  const left = arr.filter(x => x < pivot);
  const right = arr.filter(x => x > pivot);
  return [...quickSort(left), pivot, ...quickSort(right)];
}`

const STATS = [
  { label: 'Languages', value: 7 },
  { label: 'Active Typists', value: 1200, suffix: '+' },
  { label: 'Tests Completed', value: 48000, suffix: '+' },
  { label: 'Avg WPM', value: 62 },
]

const STEPS = [
  { num: '01', title: 'Choose Your Language', desc: 'Pick from 7 popular languages and set duration & difficulty.' },
  { num: '02', title: 'Type Real Code', desc: 'Practice with syntax-accurate snippets — not random words.' },
  { num: '03', title: 'Track & Compete', desc: 'Review your stats, watch your progress, climb the leaderboard.' },
]

/* ═══════════════════════════════════════════════════════════
   SUB-COMPONENTS
   ═══════════════════════════════════════════════════════════ */

/* ── Animated counter ─────────────────────────────────────── */
function Counter({ target, suffix = '', duration = 2 }) {
  const [count, setCount] = useState(0)
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-40px' })

  useEffect(() => {
    if (!inView) return
    let start = 0
    const step = Math.max(1, Math.floor(target / (duration * 60)))
    const id = setInterval(() => {
      start += step
      if (start >= target) { setCount(target); clearInterval(id) }
      else setCount(start)
    }, 1000 / 60)
    return () => clearInterval(id)
  }, [inView, target, duration])

  return (
    <span ref={ref}>
      {count.toLocaleString()}{suffix}
    </span>
  )
}

/* ── Floating particle field ──────────────────────────────── */
function ParticleField() {
  const canvasRef = useRef(null)

  useEffect(() => {
    const canvas = canvasRef.current
    const ctx = canvas.getContext('2d')
    let raf
    let w = canvas.width = window.innerWidth
    let h = canvas.height = window.innerHeight

    const particles = Array.from({ length: 60 }, () => ({
      x: Math.random() * w,
      y: Math.random() * h,
      vx: (Math.random() - 0.5) * 0.3,
      vy: (Math.random() - 0.5) * 0.3,
      r: Math.random() * 1.5 + 0.5,
      a: Math.random() * 0.4 + 0.1,
    }))

    const onResize = () => {
      w = canvas.width = window.innerWidth
      h = canvas.height = window.innerHeight
    }
    window.addEventListener('resize', onResize)

    const draw = () => {
      ctx.clearRect(0, 0, w, h)

      for (const p of particles) {
        p.x += p.vx; p.y += p.vy
        if (p.x < 0) p.x = w; if (p.x > w) p.x = 0
        if (p.y < 0) p.y = h; if (p.y > h) p.y = 0

        ctx.beginPath()
        ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2)
        ctx.fillStyle = `rgba(0,255,65,${p.a})`
        ctx.fill()
      }

      // draw connections
      for (let i = 0; i < particles.length; i++) {
        for (let j = i + 1; j < particles.length; j++) {
          const dx = particles[i].x - particles[j].x
          const dy = particles[i].y - particles[j].y
          const dist = Math.sqrt(dx * dx + dy * dy)
          if (dist < 150) {
            ctx.beginPath()
            ctx.moveTo(particles[i].x, particles[i].y)
            ctx.lineTo(particles[j].x, particles[j].y)
            ctx.strokeStyle = `rgba(0,255,65,${0.06 * (1 - dist / 150)})`
            ctx.lineWidth = 0.5
            ctx.stroke()
          }
        }
      }
      raf = requestAnimationFrame(draw)
    }
    draw()

    return () => {
      cancelAnimationFrame(raf)
      window.removeEventListener('resize', onResize)
    }
  }, [])

  return (
    <canvas
      ref={canvasRef}
      className="fixed inset-0 pointer-events-none"
      style={{ zIndex: 0, opacity: 0.5 }}
    />
  )
}

/* ── Live typing simulation ───────────────────────────────── */
function TypingDemo() {
  const [typed, setTyped] = useState(0)
  const [wpm, setWpm] = useState(0)
  const [acc, setAcc] = useState(100)
  const intervalRef = useRef(null)
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-60px' })

  useEffect(() => {
    if (!inView) return
    let i = 0
    const baseDelay = 55
    const type = () => {
      i++
      setTyped(i)
      // simulate WPM ramp up
      setWpm(Math.min(85, Math.floor(30 + (i / DEMO_CODE.length) * 55 + Math.random() * 6)))
      setAcc(Math.max(96, 100 - Math.floor(Math.random() * 4)))

      if (i >= DEMO_CODE.length) {
        clearTimeout(intervalRef.current)
        // restart after a pause
        setTimeout(() => { i = 0; setTyped(0); setWpm(0); setAcc(100); type() }, 2400)
        return
      }
      const jitter = (Math.random() - 0.5) * 40
      // slow down for special chars
      const ch = DEMO_CODE[i]
      const extra = /[{}()[\]<>.,;:=!&|]/.test(ch) ? 50 : 0
      intervalRef.current = setTimeout(type, baseDelay + jitter + extra)
    }
    type()
    return () => clearTimeout(intervalRef.current)
  }, [inView])

  const lines = DEMO_CODE.split('\n')
  let charIndex = 0

  return (
    <div ref={ref} className="landing-demo-window">
      {/* title bar */}
      <div className="landing-demo-titlebar">
        <span className="landing-dot landing-dot--red" />
        <span className="landing-dot landing-dot--yellow" />
        <span className="landing-dot landing-dot--green" />
        <span className="landing-demo-filename">quickSort.js</span>
      </div>

      {/* metrics bar */}
      <div className="landing-demo-metrics">
        <span><span className="landing-metric-label">WPM</span> <span className="landing-metric-value">{wpm}</span></span>
        <span><span className="landing-metric-label">ACC</span> <span className="landing-metric-value">{acc}%</span></span>
        <span><span className="landing-metric-label">TIME</span> <span className="landing-metric-value">0:{String(Math.floor(typed / 3)).padStart(2, '0')}</span></span>
      </div>

      {/* code area */}
      <div className="landing-demo-code">
        {lines.map((line, li) => {
          const lineStart = charIndex
          charIndex += line.length + (li < lines.length - 1 ? 1 : 0) // +1 for \n
          return (
            <div key={li} className="landing-demo-line">
              <span className="landing-demo-lineno">{li + 1}</span>
              <span>
                {line.split('').map((ch, ci) => {
                  const globalIdx = lineStart + ci
                  let cls = 'landing-ch-untyped'
                  if (globalIdx < typed) cls = 'landing-ch-correct'
                  if (globalIdx === typed) cls = 'landing-ch-cursor'
                  return <span key={ci} className={cls}>{ch}</span>
                })}
              </span>
            </div>
          )
        })}
      </div>
    </div>
  )
}

/* ── Glowing feature card ─────────────────────────────────── */
function FeatureCard({ icon, title, desc, index }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-30px' })

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 30 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.5, delay: index * 0.1, ease: 'easeOut' }}
      className="landing-feature-card"
    >
      <div className="landing-feature-icon">{icon}</div>
      <h3 className="landing-feature-title">{title}</h3>
      <p className="landing-feature-desc">{desc}</p>
    </motion.div>
  )
}

/* ═══════════════════════════════════════════════════════════
   MAIN LANDING PAGE
   ═══════════════════════════════════════════════════════════ */
export default function Landing() {
  const heroRef = useRef(null)
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ['start start', 'end start'] })
  const heroY = useTransform(scrollYProgress, [0, 1], [0, 120])
  const heroOpacity = useTransform(scrollYProgress, [0, 0.7], [1, 0])

  return (
    <div className="landing-root">
      <ParticleField />

      {/* ═══════ HERO ═══════ */}
      <section ref={heroRef} className="landing-hero">
        <motion.div
          style={{ y: heroY, opacity: heroOpacity }}
          className="landing-hero-inner"
        >
          {/* Tagline */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: 'easeOut' }}
            className="landing-hero-badge"
          >
            <span className="landing-badge-dot" />
            Built for developers, not typists
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.15, ease: 'easeOut' }}
            className="landing-hero-title"
          >
            Type <span className="landing-gradient-text">real code.</span>
            <br />
            Get <span className="landing-gradient-text">really fast.</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.35 }}
            className="landing-hero-sub"
          >
            Practice typing production-quality code in 7 languages with AI-generated
            snippets, real-time metrics, and a global leaderboard.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.55 }}
            className="landing-hero-ctas"
          >
            <Link to="/test" className="landing-btn-primary">
              <span className="landing-btn-glow" />
              Start Typing
              <span className="landing-btn-arrow">→</span>
            </Link>
            <Link to="/leaderboard" className="landing-btn-secondary">
              View Leaderboard
            </Link>
          </motion.div>

          {/* language pills */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.75 }}
            className="landing-lang-pills"
          >
            {LANGUAGES.map((l, i) => (
              <motion.span
                key={l.name}
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.8 + i * 0.06 }}
                className="landing-lang-pill"
              >
                <span className="landing-lang-icon">{l.icon}</span>
                {l.name}
              </motion.span>
            ))}
          </motion.div>
        </motion.div>
      </section>

      {/* ═══════ LIVE DEMO ═══════ */}
      <section className="landing-section">
        <SectionHeading
          tag="Live Preview"
          title="Watch it in action"
          sub="Character-by-character validation with real-time WPM tracking — just like the real thing."
        />
        <div className="landing-demo-wrap">
          <TypingDemo />
        </div>
      </section>

      {/* ═══════ FEATURES ═══════ */}
      <section className="landing-section">
        <SectionHeading
          tag="Features"
          title="Everything you need to level up"
          sub="Built with obsessive attention to what makes typing practice effective for developers."
        />
        <div className="landing-features-grid">
          {FEATURES.map((f, i) => (
            <FeatureCard key={f.title} {...f} index={i} />
          ))}
        </div>
      </section>

      {/* ═══════ HOW IT WORKS ═══════ */}
      <section className="landing-section">
        <SectionHeading
          tag="How It Works"
          title="Three steps to faster typing"
          sub="No setup required. Jump in and start improving in under a minute."
        />
        <div className="landing-steps">
          {STEPS.map((s, i) => (
            <StepCard key={s.num} {...s} index={i} />
          ))}
        </div>
      </section>

      {/* ═══════ STATS ═══════ */}
      <section className="landing-section">
        <div className="landing-stats-grid">
          {STATS.map((s) => (
            <div key={s.label} className="landing-stat-card">
              <div className="landing-stat-value">
                <Counter target={s.value} suffix={s.suffix} />
              </div>
              <div className="landing-stat-label">{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ═══════ FINAL CTA ═══════ */}
      <section className="landing-section landing-cta-section">
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.7 }}
          className="landing-cta-box"
        >
          <h2 className="landing-cta-title">
            Ready to type like you mean it?
          </h2>
          <p className="landing-cta-sub">
            Join thousands of developers sharpening their keystrokes on real code.
          </p>
          <div className="landing-hero-ctas" style={{ justifyContent: 'center' }}>
            <Link to="/test" className="landing-btn-primary">
              <span className="landing-btn-glow" />
              Start Typing — It&apos;s Free
              <span className="landing-btn-arrow">→</span>
            </Link>
            <Link to="/signup" className="landing-btn-secondary">
              Create Account
            </Link>
          </div>
        </motion.div>
      </section>

      {/* ═══════ FOOTER ═══════ */}
      <footer className="landing-footer">
        <div className="landing-footer-inner">
          <span style={{ opacity: 0.5 }}>&gt;_</span>{' '}
          <span className="glow-text" style={{ fontWeight: 700 }}>typing.dev</span>
          <span className="landing-footer-sep">·</span>
          <span style={{ opacity: 0.35 }}>Built for developers who take their craft seriously.</span>
        </div>
      </footer>
    </div>
  )
}

/* ── Section heading ──────────────────────────────────────── */
function SectionHeading({ tag, title, sub }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-50px' })

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 30 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6 }}
      className="landing-section-heading"
    >
      <span className="landing-section-tag">{tag}</span>
      <h2 className="landing-section-title">{title}</h2>
      {sub && <p className="landing-section-sub">{sub}</p>}
    </motion.div>
  )
}

/* ── Step card ────────────────────────────────────────────── */
function StepCard({ num, title, desc, index }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-40px' })

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, x: -30 }}
      animate={inView ? { opacity: 1, x: 0 } : {}}
      transition={{ duration: 0.5, delay: index * 0.15 }}
      className="landing-step-card"
    >
      <div className="landing-step-num">{num}</div>
      <div>
        <h3 className="landing-step-title">{title}</h3>
        <p className="landing-step-desc">{desc}</p>
      </div>
    </motion.div>
  )
}
