import { useState, useEffect, useRef, useMemo, useCallback } from 'react'
import { Link } from 'react-router-dom'
import { motion, useInView, useScroll, useTransform, useMotionValue, useSpring, AnimatePresence } from 'framer-motion'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { Points, PointMaterial, Float, MeshDistortMaterial, Sphere } from '@react-three/drei'
import * as THREE from 'three'

/* ═══════════════════════════════════════════════════════════
   CONSTANTS
   ═══════════════════════════════════════════════════════════ */

const LANGUAGES = [
  { name: 'JavaScript', ext: '.js',  icon: '{ }' },
  { name: 'TypeScript', ext: '.ts',  icon: '<T>' },
  { name: 'Python',     ext: '.py',  icon: '#!'  },
  { name: 'Java',       ext: '.java',icon: '::' },
  { name: 'Go',         ext: '.go',  icon: ':=' },
  { name: 'Rust',       ext: '.rs',  icon: '&mut' },
  { name: 'C++',        ext: '.cpp', icon: '<<' },
]

const FEATURES = [
  {
    title: 'Real-Time Metrics',
    desc: 'WPM, raw WPM, accuracy and error count — updated on every keystroke with smooth live charts.',
    icon: '▸ _',
  },
  {
    title: 'AI-Powered Snippets',
    desc: 'Fresh, syntax-accurate code generated by Google Gemini. Never practice the same snippet twice.',
    icon: '⚡',
  },
  {
    title: 'Global Leaderboard',
    desc: 'Compete with developers worldwide. Per-language rankings with podium display for the top 3.',
    icon: '🏆',
  },
  {
    title: 'Personal Analytics',
    desc: 'GitHub-style activity heatmap, per-duration breakdowns, consistency scores and progress tracking.',
    icon: '📊',
  },
  {
    title: 'Multiple Durations',
    desc: 'Sprint or endurance — choose 15s, 30s, 60s or 120s tests to match your training goals.',
    icon: '⏱',
  },
  {
    title: 'Difficulty Levels',
    desc: 'Easy, medium or hard. Scale the complexity from simple functions to advanced algorithms.',
    icon: '◈',
  },
]

const DEMO_CODE = `function quickSort(arr) {
  if (arr.length <= 1) return arr;
  const pivot = arr[0];
  const left = arr.filter(x => x < pivot);
  const right = arr.filter(x => x > pivot);
  return [...quickSort(left), pivot, ...quickSort(right)];
}`

const STATS = [
  { label: 'Languages', value: 7 },
  { label: 'Active Typists', value: 1200, suffix: '+' },
  { label: 'Tests Completed', value: 48000, suffix: '+' },
  { label: 'Avg WPM', value: 62 },
]

const STEPS = [
  { num: '01', title: 'Choose Your Language', desc: 'Pick from 7 popular languages and set duration & difficulty.' },
  { num: '02', title: 'Type Real Code', desc: 'Practice with syntax-accurate snippets — not random words.' },
  { num: '03', title: 'Track & Compete', desc: 'Review your stats, watch your progress, climb the leaderboard.' },
]

const SCRAMBLE_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*<>[]{}/'

const TESTIMONIALS = [
  { name: 'Alex K.', role: 'Full-Stack Dev', text: 'Went from 45 to 78 WPM in 3 weeks. The AI snippets keep it fresh.', wpm: 78 },
  { name: 'Sarah M.', role: 'DevOps Engineer', text: 'Finally a typing trainer that uses real code, not "the quick brown fox".', wpm: 92 },
  { name: 'James L.', role: 'CS Student', text: 'The leaderboard keeps me coming back. Addictive in the best way.', wpm: 65 },
]

/* ═══════════════════════════════════════════════════════════
   THREE.JS COMPONENTS
   ═══════════════════════════════════════════════════════════ */

function StarField({ count = 3000 }) {
  const points = useRef()
  const positions = useMemo(() => {
    const pos = new Float32Array(count * 3)
    for (let i = 0; i < count; i++) {
      pos[i * 3] = (Math.random() - 0.5) * 20
      pos[i * 3 + 1] = (Math.random() - 0.5) * 20
      pos[i * 3 + 2] = (Math.random() - 0.5) * 20
    }
    return pos
  }, [count])

  useFrame((state, delta) => {
    if (points.current) {
      points.current.rotation.x -= delta * 0.02
      points.current.rotation.y -= delta * 0.03
    }
  })

  return (
    <group rotation={[0, 0, Math.PI / 4]}>
      <Points ref={points} positions={positions} stride={3} frustumCulled={false}>
        <PointMaterial transparent color="#00FF41" size={0.015} sizeAttenuation depthWrite={false} opacity={0.6} />
      </Points>
    </group>
  )
}

function MorphOrb() {
  const meshRef = useRef()
  useFrame((state) => {
    if (meshRef.current) {
      meshRef.current.rotation.x = state.clock.elapsedTime * 0.15
      meshRef.current.rotation.y = state.clock.elapsedTime * 0.2
    }
  })
  return (
    <Float speed={1.5} rotationIntensity={0.3} floatIntensity={0.8}>
      <Sphere ref={meshRef} args={[1.5, 64, 64]} position={[0, 0, 0]}>
        <MeshDistortMaterial
          color="#003300" emissive="#00FF41" emissiveIntensity={0.15}
          roughness={0.3} metalness={0.8} distort={0.4} speed={2}
          transparent opacity={0.35} wireframe
        />
      </Sphere>
    </Float>
  )
}

function GridFloor() {
  const meshRef = useRef()
  useFrame((state) => {
    if (meshRef.current) meshRef.current.position.z = (state.clock.elapsedTime * 0.3) % 1
  })
  return <gridHelper ref={meshRef} args={[40, 40, '#003300', '#001a00']} position={[0, -4, 0]} />
}

function CameraRig() {
  const { camera } = useThree()
  const mouseX = useRef(0)
  const mouseY = useRef(0)
  useEffect(() => {
    const handle = (e) => {
      mouseX.current = (e.clientX / window.innerWidth - 0.5) * 2
      mouseY.current = (e.clientY / window.innerHeight - 0.5) * 2
    }
    window.addEventListener('mousemove', handle)
    return () => window.removeEventListener('mousemove', handle)
  }, [])
  useFrame(() => {
    camera.position.x += (mouseX.current * 0.5 - camera.position.x) * 0.02
    camera.position.y += (-mouseY.current * 0.3 - camera.position.y) * 0.02
    camera.lookAt(0, 0, 0)
  })
  return null
}

function Scene3D() {
  return (
    <div className="landing-3d-bg">
      <Canvas camera={{ position: [0, 0, 5], fov: 60 }} dpr={[1, 1.5]} gl={{ antialias: false, alpha: true }} style={{ background: 'transparent' }}>
        <fog attach="fog" args={['#000A00', 5, 25]} />
        <ambientLight intensity={0.2} />
        <pointLight position={[10, 10, 10]} color="#00FF41" intensity={0.5} />
        <StarField />
        <MorphOrb />
        <GridFloor />
        <CameraRig />
      </Canvas>
    </div>
  )
}

/* ═══════════════════════════════════════════════════════════
   VISUAL EFFECTS COMPONENTS
   ═══════════════════════════════════════════════════════════ */

function ScrambleText({ text, className, delay = 0 }) {
  const [displayed, setDisplayed] = useState('')
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-40px' })
  const hasRun = useRef(false)

  useEffect(() => {
    if (!inView || hasRun.current) return
    hasRun.current = true
    let iteration = 0
    const maxIterations = text.length
    const timeout = setTimeout(() => {
      const interval = setInterval(() => {
        setDisplayed(
          text.split('').map((char, i) => {
            if (char === ' ') return ' '
            if (i < iteration) return text[i]
            return SCRAMBLE_CHARS[Math.floor(Math.random() * SCRAMBLE_CHARS.length)]
          }).join('')
        )
        iteration += 1 / 2
        if (iteration >= maxIterations) { setDisplayed(text); clearInterval(interval) }
      }, 30)
      return () => clearInterval(interval)
    }, delay)
    return () => clearTimeout(timeout)
  }, [inView, text, delay])

  return <span ref={ref} className={className}>{displayed || '\u00A0'}</span>
}

function GlitchText({ children, className }) {
  return (
    <span className={`landing-glitch ${className || ''}`} data-text={children}>
      {children}
    </span>
  )
}

function MagneticButton({ children, className, ...props }) {
  const ref = useRef(null)
  const x = useMotionValue(0)
  const y = useMotionValue(0)
  const springX = useSpring(x, { stiffness: 150, damping: 15 })
  const springY = useSpring(y, { stiffness: 150, damping: 15 })

  const handleMouse = (e) => {
    const rect = ref.current?.getBoundingClientRect()
    if (!rect) return
    x.set((e.clientX - (rect.left + rect.width / 2)) * 0.3)
    y.set((e.clientY - (rect.top + rect.height / 2)) * 0.3)
  }
  const reset = () => { x.set(0); y.set(0) }

  return (
    <motion.div ref={ref} style={{ x: springX, y: springY, display: 'inline-block' }} onMouseMove={handleMouse} onMouseLeave={reset}>
      <Link className={className} {...props}>{children}</Link>
    </motion.div>
  )
}

function TiltCard({ children, className }) {
  const ref = useRef(null)
  const rotateX = useMotionValue(0)
  const rotateY = useMotionValue(0)
  const springRX = useSpring(rotateX, { stiffness: 200, damping: 20 })
  const springRY = useSpring(rotateY, { stiffness: 200, damping: 20 })

  const handleMouse = (e) => {
    const rect = ref.current?.getBoundingClientRect()
    if (!rect) return
    rotateX.set(((e.clientY - rect.top) / rect.height - 0.5) * -15)
    rotateY.set(((e.clientX - rect.left) / rect.width - 0.5) * 15)
  }
  const reset = () => { rotateX.set(0); rotateY.set(0) }

  return (
    <motion.div
      ref={ref} className={className}
      style={{ rotateX: springRX, rotateY: springRY, transformPerspective: 800, transformStyle: 'preserve-3d' }}
      onMouseMove={handleMouse} onMouseLeave={reset}
    >{children}</motion.div>
  )
}

function Counter({ target, suffix = '', duration = 2 }) {
  const [count, setCount] = useState(0)
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-40px' })
  useEffect(() => {
    if (!inView) return
    let start = 0
    const step = Math.max(1, Math.floor(target / (duration * 60)))
    const id = setInterval(() => {
      start += step
      if (start >= target) { setCount(target); clearInterval(id) }
      else setCount(start)
    }, 1000 / 60)
    return () => clearInterval(id)
  }, [inView, target, duration])
  return <span ref={ref}>{count.toLocaleString()}{suffix}</span>
}

function ScrollProgress() {
  const { scrollYProgress } = useScroll()
  const scaleX = useSpring(scrollYProgress, { stiffness: 100, damping: 30 })
  return <motion.div className="landing-scroll-progress" style={{ scaleX }} />
}

function NoiseOverlay() {
  return <div className="landing-noise" aria-hidden="true" />
}

function TypingDemo() {
  const [typed, setTyped] = useState(0)
  const [wpm, setWpm] = useState(0)
  const [acc, setAcc] = useState(100)
  const intervalRef = useRef(null)
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-60px' })

  useEffect(() => {
    if (!inView) return
    let i = 0
    const baseDelay = 55
    const type = () => {
      i++
      setTyped(i)
      setWpm(Math.min(85, Math.floor(30 + (i / DEMO_CODE.length) * 55 + Math.random() * 6)))
      setAcc(Math.max(96, 100 - Math.floor(Math.random() * 4)))
      if (i >= DEMO_CODE.length) {
        clearTimeout(intervalRef.current)
        setTimeout(() => { i = 0; setTyped(0); setWpm(0); setAcc(100); type() }, 2400)
        return
      }
      const jitter = (Math.random() - 0.5) * 40
      const ch = DEMO_CODE[i]
      const extra = /[{}()[\]<>.,;:=!&|]/.test(ch) ? 50 : 0
      intervalRef.current = setTimeout(type, baseDelay + jitter + extra)
    }
    type()
    return () => clearTimeout(intervalRef.current)
  }, [inView])

  const lines = DEMO_CODE.split('\n')
  let charIndex = 0

  return (
    <div ref={ref} className="landing-demo-window">
      <div className="landing-demo-titlebar">
        <span className="landing-dot landing-dot--red" />
        <span className="landing-dot landing-dot--yellow" />
        <span className="landing-dot landing-dot--green" />
        <span className="landing-demo-filename">quickSort.js</span>
        <div className="landing-demo-pulse" />
      </div>
      <div className="landing-demo-metrics">
        <span><span className="landing-metric-label">WPM</span> <span className="landing-metric-value">{wpm}</span></span>
        <span><span className="landing-metric-label">ACC</span> <span className="landing-metric-value">{acc}%</span></span>
        <span><span className="landing-metric-label">TIME</span> <span className="landing-metric-value">0:{String(Math.floor(typed / 3)).padStart(2, '0')}</span></span>
        <div className="landing-demo-wpm-bar">
          <motion.div className="landing-demo-wpm-fill" animate={{ width: `${Math.min(100, (wpm / 100) * 100)}%` }} transition={{ duration: 0.3 }} />
        </div>
      </div>
      <div className="landing-demo-code">
        {lines.map((line, li) => {
          const lineStart = charIndex
          charIndex += line.length + (li < lines.length - 1 ? 1 : 0)
          return (
            <div key={li} className="landing-demo-line">
              <span className="landing-demo-lineno">{li + 1}</span>
              <span>
                {line.split('').map((ch, ci) => {
                  const globalIdx = lineStart + ci
                  let cls = 'landing-ch-untyped'
                  if (globalIdx < typed) cls = 'landing-ch-correct'
                  if (globalIdx === typed) cls = 'landing-ch-cursor'
                  return <span key={ci} className={cls}>{ch}</span>
                })}
              </span>
            </div>
          )
        })}
      </div>
    </div>
  )
}

function FeatureCard({ icon, title, desc, index }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-30px' })
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 40, rotateX: 10 }}
      animate={inView ? { opacity: 1, y: 0, rotateX: 0 } : {}}
      transition={{ duration: 0.6, delay: index * 0.1, ease: [0.16, 1, 0.3, 1] }}
    >
      <TiltCard className="landing-feature-card">
        <div className="landing-feature-card-glow" />
        <div className="landing-feature-icon">{icon}</div>
        <h3 className="landing-feature-title">{title}</h3>
        <p className="landing-feature-desc">{desc}</p>
        <div className="landing-feature-border-anim" />
      </TiltCard>
    </motion.div>
  )
}

function TestimonialCard({ name, role, text, wpm, index }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-30px' })
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 30, scale: 0.95 }}
      animate={inView ? { opacity: 1, y: 0, scale: 1 } : {}}
      transition={{ duration: 0.5, delay: index * 0.15, ease: [0.16, 1, 0.3, 1] }}
      className="landing-testimonial-card"
    >
      <div className="landing-testimonial-quote">&ldquo;</div>
      <p className="landing-testimonial-text">{text}</p>
      <div className="landing-testimonial-footer">
        <div>
          <div className="landing-testimonial-name">{name}</div>
          <div className="landing-testimonial-role">{role}</div>
        </div>
        <div className="landing-testimonial-wpm">{wpm} <span>WPM</span></div>
      </div>
    </motion.div>
  )
}

function SectionHeading({ tag, title, sub }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-50px' })
  return (
    <motion.div ref={ref} initial={{ opacity: 0, y: 30 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }} className="landing-section-heading">
      <span className="landing-section-tag">{tag}</span>
      <h2 className="landing-section-title"><ScrambleText text={title} delay={200} /></h2>
      {sub && <p className="landing-section-sub">{sub}</p>}
    </motion.div>
  )
}

function StepCard({ num, title, desc, index }) {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-40px' })
  return (
    <motion.div ref={ref} initial={{ opacity: 0, x: -40 }} animate={inView ? { opacity: 1, x: 0 } : {}} transition={{ duration: 0.6, delay: index * 0.15, ease: [0.16, 1, 0.3, 1] }} className="landing-step-card">
      <div className="landing-step-num">{num}</div>
      <div className="landing-step-connector" />
      <div>
        <h3 className="landing-step-title">{title}</h3>
        <p className="landing-step-desc">{desc}</p>
      </div>
    </motion.div>
  )
}

function FloatingCode() {
  const lines = [
    'const speed = measure()', 'fn main() { loop {} }', 'import asyncio',
    'System.out.print()', 'go func() {}()', 'impl Iterator for',
    'export default App', 'while (true) { type }',
  ]
  return (
    <div className="landing-floating-code" aria-hidden="true">
      {lines.map((line, i) => (
        <motion.div
          key={i} className="landing-floating-line"
          initial={{ opacity: 0 }}
          animate={{ opacity: [0, 0.12, 0.12, 0], x: [0, 20, 20, 40], y: [0, -10, -10, -20] }}
          transition={{ duration: 8, delay: i * 1.2, repeat: Infinity, ease: 'linear' }}
          style={{ top: `${10 + (i * 11) % 80}%`, left: `${5 + (i * 17) % 85}%`, fontSize: `${0.55 + Math.random() * 0.25}rem` }}
        >{line}</motion.div>
      ))}
    </div>
  )
}

/* ═══════════════════════════════════════════════════════════
   MAIN LANDING PAGE
   ═══════════════════════════════════════════════════════════ */
export default function Landing() {
  const heroRef = useRef(null)
  const { scrollYProgress } = useScroll({ target: heroRef, offset: ['start start', 'end start'] })
  const heroY = useTransform(scrollYProgress, [0, 1], [0, 150])
  const heroOpacity = useTransform(scrollYProgress, [0, 0.6], [1, 0])
  const heroScale = useTransform(scrollYProgress, [0, 0.6], [1, 0.95])

  return (
    <div className="landing-root">
      <ScrollProgress />
      <NoiseOverlay />
      <Scene3D />
      <FloatingCode />

      {/* ═══════ HERO ═══════ */}
      <section ref={heroRef} className="landing-hero">
        <motion.div style={{ y: heroY, opacity: heroOpacity, scale: heroScale }} className="landing-hero-inner">
          <motion.div
            initial={{ opacity: 0, y: 30, filter: 'blur(10px)' }}
            animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            className="landing-hero-badge"
          >
            <span className="landing-badge-dot" />
            Built for developers, not typists
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 50, filter: 'blur(10px)' }}
            animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
            transition={{ duration: 1, delay: 0.15, ease: [0.16, 1, 0.3, 1] }}
            className="landing-hero-title"
          >
            Type <GlitchText className="landing-gradient-text">real code.</GlitchText>
            <br />
            Get <GlitchText className="landing-gradient-text">really fast.</GlitchText>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 30, filter: 'blur(8px)' }}
            animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
            transition={{ duration: 0.8, delay: 0.35 }}
            className="landing-hero-sub"
          >
            Practice typing production-quality code in 7 languages with AI-generated
            snippets, real-time metrics, and a global leaderboard.
          </motion.p>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.55 }} className="landing-hero-ctas">
            <MagneticButton to="/test" className="landing-btn-primary">
              <span className="landing-btn-glow" />
              <span className="landing-btn-shimmer" />
              Start Typing
              <span className="landing-btn-arrow">→</span>
            </MagneticButton>
            <MagneticButton to="/leaderboard" className="landing-btn-secondary">
              View Leaderboard
            </MagneticButton>
          </motion.div>

          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.8, delay: 0.75 }} className="landing-lang-pills">
            {LANGUAGES.map((l, i) => (
              <motion.span
                key={l.name}
                initial={{ opacity: 0, scale: 0.8, filter: 'blur(4px)' }}
                animate={{ opacity: 1, scale: 1, filter: 'blur(0px)' }}
                transition={{ delay: 0.8 + i * 0.07, duration: 0.4 }}
                className="landing-lang-pill"
                whileHover={{ scale: 1.1, borderColor: 'rgba(0,255,65,0.5)' }}
              >
                <span className="landing-lang-icon">{l.icon}</span>
                {l.name}
              </motion.span>
            ))}
          </motion.div>
        </motion.div>

        <motion.div className="landing-scroll-hint" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.5 }}>
          <motion.div animate={{ y: [0, 8, 0] }} transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}>
            <span className="landing-scroll-arrow">↓</span>
          </motion.div>
          <span className="landing-scroll-label">scroll to explore</span>
        </motion.div>
      </section>

      {/* ═══════ LIVE DEMO ═══════ */}
      <section className="landing-section">
        <SectionHeading tag="Live Preview" title="Watch it in action" sub="Character-by-character validation with real-time WPM tracking — just like the real thing." />
        <div className="landing-demo-wrap">
          <motion.div
            initial={{ opacity: 0, y: 40, rotateX: 8 }}
            whileInView={{ opacity: 1, y: 0, rotateX: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            style={{ transformPerspective: 1200 }}
          >
            <TypingDemo />
          </motion.div>
        </div>
      </section>

      {/* ═══════ FEATURES ═══════ */}
      <section className="landing-section">
        <SectionHeading tag="Features" title="Everything you need to level up" sub="Built with obsessive attention to what makes typing practice effective for developers." />
        <div className="landing-features-grid">
          {FEATURES.map((f, i) => <FeatureCard key={f.title} {...f} index={i} />)}
        </div>
      </section>

      {/* ═══════ HOW IT WORKS ═══════ */}
      <section className="landing-section">
        <SectionHeading tag="How It Works" title="Three steps to faster typing" sub="No setup required. Jump in and start improving in under a minute." />
        <div className="landing-steps">
          {STEPS.map((s, i) => <StepCard key={s.num} {...s} index={i} />)}
        </div>
      </section>

      {/* ═══════ STATS ═══════ */}
      <section className="landing-section">
        <div className="landing-stats-grid">
          {STATS.map((s, i) => (
            <motion.div
              key={s.label} className="landing-stat-card"
              initial={{ opacity: 0, y: 30, scale: 0.9 }}
              whileInView={{ opacity: 1, y: 0, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              whileHover={{ scale: 1.05, borderColor: 'rgba(0,255,65,0.3)' }}
            >
              <div className="landing-stat-value"><Counter target={s.value} suffix={s.suffix} /></div>
              <div className="landing-stat-label">{s.label}</div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ═══════ TESTIMONIALS ═══════ */}
      <section className="landing-section">
        <SectionHeading tag="Community" title="Developers love typing.dev" sub="Join thousands of developers who have made typing.dev part of their daily routine." />
        <div className="landing-testimonials-grid">
          {TESTIMONIALS.map((t, i) => <TestimonialCard key={t.name} {...t} index={i} />)}
        </div>
      </section>

      {/* ═══════ FINAL CTA ═══════ */}
      <section className="landing-section landing-cta-section">
        <motion.div initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-60px' }} transition={{ duration: 0.7 }} className="landing-cta-box">
          <div className="landing-cta-orb" />
          <h2 className="landing-cta-title"><ScrambleText text="Ready to type like you mean it?" delay={300} /></h2>
          <p className="landing-cta-sub">Join thousands of developers sharpening their keystrokes on real code.</p>
          <div className="landing-hero-ctas" style={{ justifyContent: 'center' }}>
            <MagneticButton to="/test" className="landing-btn-primary">
              <span className="landing-btn-glow" />
              <span className="landing-btn-shimmer" />
              Start Typing — It&apos;s Free
              <span className="landing-btn-arrow">→</span>
            </MagneticButton>
            <MagneticButton to="/signup" className="landing-btn-secondary">
              Create Account
            </MagneticButton>
          </div>
        </motion.div>
      </section>

      {/* ═══════ FOOTER ═══════ */}
      <footer className="landing-footer">
        <div className="landing-footer-inner">
          <span style={{ opacity: 0.5 }}>&gt;_</span>{' '}
          <span className="glow-text" style={{ fontWeight: 700 }}>typing.dev</span>
          <span className="landing-footer-sep">·</span>
          <span style={{ opacity: 0.35 }}>Built for developers who take their craft seriously.</span>
        </div>
      </footer>
    </div>
  )
}
